// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HrLeaveManagement.Domain.Models;

public partial class LeaveRequest
{
    public int Id { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? DateRequested { get; set; }

    public string RequestComments { get; set; }

    public DateTime? DateActioned { get; set; }

    public bool? Approved { get; set; }

    public bool? Cancelled { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public int? LeaveTypeId { get; set; }

    public virtual LeaveType LeaveType { get; set; }
}