// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HrLeaveManagement.Domain.Models;

public partial class LeaveAllocation
{
    public int Id { get; set; }

    public int? NumberOfDays { get; set; }

    public int? Period { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModifiedDate { get; set; }

    public string LastModifiedBy { get; set; }

    public int LeaveTypeId { get; set; }

    public virtual LeaveType LeaveType { get; set; }
}